apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      apprs: kubia-rs
  template:
    metadata:
      labels:
        apprs: kubia-rs
    spec:
      containers:
      - name: kubia-rs
        image: luksa/kubia
